### PR TITLE
Updates .gitignore file.

### PR DESCRIPTION
**Pull request by konstantp**
Ignores files which Sublime creates for project management.

### CODE REVIEW

**Comment by anrw** [comment]
I am not sure if it's good to keep all possible environment files inside Classy `.gitignore`. Instead I think we need to keep only those which are related to Classy development.

**Comment by LehaMotovilov** [comment]
Agree with @anrw but we can add IDE files like .idea/ or sublime-project to ignore file.

**Comment by LehaMotovilov** [comment]
@konstantp remove all files exclude IDE stuff and add PHPStorm files please.

**Comment by LehaMotovilov** [comment]
@konstantp Thanks! 
@anrw I think now we can merge this request into master?

**Comment by anrw** [comment]
@LehaMotovilov right!

**Comment by anrw** [comment]
Btw, I think we can also get rid of node_modules too :)

**Pull request merged**
